#ifndef ALGORITMOGPAG_GLOBAL_H
#define ALGORITMOGPAG_GLOBAL_H

#include <QtCore/qglobal.h>
#if defined(ALGORITMOGPAG_LIBRARY)
#  define ALGORITMOGPAGSHARED_EXPORT Q_DECL_EXPORT
#else
#  define ALGORITMOGPAGSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // ALGORITMOGPAG_GLOBAL_H
